plugin {
    hyprexpo {
	overview = yes

        columns = 2

        gap_size = 20
	scale_factor = 0.30

	curvature = 0
        perspective = 0

	inactive_opacity = 0.55
        background_color = rgba(000000dd)
        blur = yes
        animation_speed = 0.85

        #bg_col = rgb(111111)
        #workspace_method = center current # [center/first] [workspace] e.g. first 1 or center m+1
	align = center
        gesture_distance = 300 # how far is the "max" for the gesture
    }
}