#####################
### LOOK AND FEEL ###
#####################

# Refer to https://wiki.hypr.land/Configuring/Variables/

# https://wiki.hypr.land/Configuring/Variables/#general

source = ~/.config/hypr-local/ScrollingToggle/scrolling-toggle.conf

# https://wiki.hypr.land/Configuring/Variables/#decoration
decoration {
    rounding = 6
    rounding_power = 2

    # Change transparency of focused and unfocused windows
    active_opacity = 0.9
    inactive_opacity = 0.9

    shadow {
        enabled = true
        range = 6
        render_power = 2
        color = rgba(2a2a2a66)  #original setting 1a1a1aee
    }

    # https://wiki.hypr.land/Configuring/Variables/#blur
    blur {
        enabled = true
        size = 8
        passes = 2

        vibrancy = 0.1696
    }
}

# https://wiki.hypr.land/Configuring/Variables/#animations
animations {
    enabled = yes, please :)

    # Default animations, see https://wiki.hypr.land/Configuring/Animations/ for more

    bezier = easeOutQuint, 0.23, 1, 0.32, 1
    bezier = easeInOutCubic, 0.65, 0.05, 0.36, 1
    bezier = linear, 0, 0, 1, 1
    bezier = almostLinear, 0.5, 0.5, 0.75, 1.0
    bezier = quick, 0.15, 0, 0.1, 1
    bezier = bez, 0.05, 0.9, 0.1, 1.05 

    animation = global, 1, 10, default
    animation = border, 1, 3.0, easeOutQuint
    animation = windows, 1, 2.0, easeOutQuint, gnomed
    animation = windowsIn, 1, 7, easeOutQuint, popin 87%
    animation = windowsOut, 1, 1.49, easeOutQuint, slide 87%
    animation = fadeIn, 1, 1.73, almostLinear
    animation = fadeOut, 1, 1.46, almostLinear
    animation = fade, 1, 1.0, quick
    animation = layers, 1, 1, quick, slide
    animation = layersIn, 1, 1, quick, slide
    animation = layersOut, 1, 1, quick, slide
    animation = workspaces, 1, 1, quick, slidefade
    animation = workspacesIn, 1, 1, quick, slidefade
    animation = workspacesOut, 1, 1, quick, slidefade
}

# Ref https://wiki.hypr.land/Configuring/Workspace-Rules/
# "Smart gaps" / "No gaps when only"
# uncomment all if you wish to use that.
# workspace = w[tv1], gapsout:0, gapsin:0
# workspace = f[1], gapsout:0, gapsin:0
# windowrule = bordersize 0, floating:0, onworkspace:w[tv1]
# windowrule = rounding 0, floating:0, onworkspace:w[tv1]
# windowrule = bordersize 0, floating:0, onworkspace:f[1]
# windowrule = rounding 0, floating:0, onworkspace:f[1]

# See https://wiki.hypr.land/Configuring/Dwindle-Layout/ for more
dwindle {
    pseudotile = true # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = true # You probably want this
}

# See https://wiki.hypr.land/Configuring/Master-Layout/ for more
master {
    new_status = master
}

# https://wiki.hypr.land/Configuring/Variables/#misc
misc {
    force_default_wallpaper = 0 # Set to 0 or 1 to disable the anime mascot wallpapers
    disable_hyprland_logo = true # If true disables the random hyprland logo / anime girl background. :(
}

source = ~/.config/hypr/scrolling.conf
