-------------------------
-- LOCAL WINDOW RULES  --
-------------------------
-- Loads rule tables generated by hypr-rule-recorder.sh from
-- ~/.config/hypr-local/windowrules/{floating,tiled}.lua
--
-- dofile() is used instead of require() on purpose: require() caches the
-- module on first load and will NOT pick up changes written by the
-- recorder script without a full Hyprland restart. dofile() re-executes
-- the file fresh every time this module is loaded, which lines up with
-- triggering `hyprctl reload` after running the recorder.

local rule_dir = os.getenv("HOME") .. "/.config/hypr-local/windowrules/"

local function load_rules(filename)
	local path = rule_dir .. filename .. ".lua"
	local ok, rules_or_err = pcall(dofile, path)

	if not ok then
		print("windowrules-local: failed to load " .. path .. ": " .. tostring(rules_or_err))
		return
	end

	if type(rules_or_err) ~= "table" then
		print("windowrules-local: " .. path .. " did not return a table, skipping")
		return
	end

	for i, rule in ipairs(rules_or_err) do
		local rule_ok, rule_err = pcall(hl.window_rule, rule)
		if not rule_ok then
			print("windowrules-local: rule #" .. i .. " in " .. path
				.. " (name=" .. tostring(rule.name) .. ") failed: " .. tostring(rule_err))
		end
	end
end

load_rules("floating")
load_rules("tiled")