##############################
### WINDOWS AND WORKSPACES ###
##############################

source = ~/.config/hypr/wrules-standard.conf

source = ~/.config/hypr-local-windowrules/floating.conf
source = ~/.config/hypr-local-windowrules/tiled.conf
