##############################
### WINDOWS AND WORKSPACES ###
##############################

##### BY CLASS #######

windowrule {
    name = Pithos
    match:class = ^pithos$

    workspace = 1
    float = on
    size = 348 740
    move = 9 35
}

windowrule {
    name = Cavalier
    match:class = ^org.nickvision.cavalier$

    workspace = 1
    float = on
    size = 348 284
    move = 9 787
}

windowrule {
    name = Clocks
    match:class = ^org.gnome.clocks$

<<<<<<< HEAD
# Gnome-Weather
#windowrulev2 = workspace 1,class:^(org.gnome.Weather)$
windowrulev2 = float,class:^(org.gnome.Weather)$
windowrulev2 = size 988 506,class:^(org.gnome.Weather)$
windowrulev2 = move 431 246,class:^(org.gnome.Weather)$
=======
    workspace = 1
    float = on
    size = 674 305
    move = 1237 766
}
>>>>>>> 00986bb (updated some configs to adjust for latest hyprland update. fixes window syntax and hyprpaper syntax. overall easier to understand)

windowrule {
    name = Weather
    match:class = ^org.gnome.Weather$

    float = on
    size = 989 506
    move = 448 38
}

windowrule {
    name = Impala
    match:class = ^Impala$

    float = on
    size = 800 600
    move = 560 253
}

windowrule {
    name = Wiremix
    match:class = ^Wiremix$

    float = on
    size = 800 600
    move = 560 253
}

windowrule {
    name = Bluetooth
    match:class = ^blueman-manager$

    float = on
    size = 535 535
    move = 641 242
}

windowrule {
    name = Yad
    match:class = ^yad$

    float = on
    size = 654 251
    move = 614 344
}

windowrule {
    name = Zenity
    match:class = ^zenity$

    pin = on
}

windowrule {
    name = Thunderbird
    match:class = ^thunderbird$

    workspace = 2
}

windowrule {
    name = ThunderbirdFlatpak
    match:class = ^org.mozilla.Thunderbird$

    workspace = 2
}

##### BY CLASS & TITLE #######

windowrule {
    name = Btop
    match:class = ^kitty$
    match:title = ^btop$

    workspace = 1
    float = on
    size = 856 1036
    move = 369 35
}

windowrule {
    name = Fastfetch
    match:class = ^kitty$
    match:title = ^fastfetch$

    workspace = 1
    float = on
    size = 674 719
    move = 1237 35
}

##### WEB APPS #######

windowrule {
    name = YouTube
    match:class = ^brave-youtube\.com__-Default$

    workspace = 4
}

windowrule {
    name = ChatGPT
    match:class = ^chrome-chat\.openai\.com__-Default$

    workspace = 3
}

windowrule {
    name = HyprlandWiki
    match:class = ^chrome-wiki\.hyprland\.org__-Default$

    workspace = 5
}

windowrule {
    name = GitHub
    match:class = ^chrome-github\.com__SystemWave8_Wave8-Hypr-Dotfiles-Default$

    workspace = 6
}
